### ISSUE TITLE
Crash on attaching hoppers to bottom of machines in 1.10.2.

### ISSUE THREAD

**Issue by meanRat** [TechReborn/RebornCore#41]
There was a bug reported about attaching hoppers in a 1.9.x version.  I am having this same issue on the 1.10.2 - 2.13.3.119 core and the tech reborn 1.10.2-1.4.172.  It is currently keeping me from loading my world.  Has this been seen or addressed on the 1.10.2 version?

I can include a crash report if needed.

**Comment by modmuss50** [comment]
What reborn core version?

**Comment by meanRat** [comment]
The one I said.  (?)  " I am having this same issue on the 1.10.2 - 2.13.3.119 core and the..."

**Comment by ali1234** [comment]
"This is a bug in older versions of Forge. It is fixed in newer versions. "

 - http://www.minecraftforge.net/forum/topic/59813-all-the-mods-crash/

The crash from this log happened because something tried to log a message with the string "%M" in it, which was interpreted as an invalid format specifier. The log message level was severe, but the real reason why it was sent is lost.
