### ISSUE TITLE
crash after breaking a blokc while testing (1.11.2)

### ISSUE THREAD

**Issue by SDUBZ** [TechReborn/RebornCore#43]
i was in my testing world and had a techreborn solar panel feeding into a mekfarm tree farm and got this crash after breaking a block

crash report:
[crash-2017-03-05_11.40.07-client.txt](https://github.com/TechReborn/RebornCore/files/819026/crash-2017-03-05_11.40.07-client.txt)

forge:1.11.2-2252

mods used in testing when crashed occured

reborncore: RebornCore-1.11.2-2.13.4.37-universal
tech reborn: TechReborn-1.11.2-2.1.6.76-universal
mek farm: mekfarm-1.11.2-0.3.0

**Comment by ali1234** [comment]
This crash was caused by this line of code:

`TeslaUtils.distributePowerToAllFaces(powerAcceptor.getWorld(), powerAcceptor.getPos(), (long) powerAcceptor.getMaxOutput(), false);`

Either `powerAcceptor.getWorld()` or `powerAcceptor.getPos()` must have returned Null here. Was it by any chance the solar panel that you broke, thus invalidating its position and world?

Since https://github.com/TechReborn/RebornCore/commit/0cb1ac18fbbc6c2341d5fce57dddd82e02faaf5e this line of code no longer exists, but the new implementation still calls `powerAcceptor.getWorld()` and `powerAcceptor.getPos()`, so it is possible this bug still exists in a different form.

**Comment by modmuss50** [comment]
Should be
